### ISSUE TITLE
Gemification

### ISSUE THREAD

**Issue by iain** [marceldegraaf/mustacci#9]
Let's start the discussion:

I propose we make mustacci into a gem.

Some considerations:
- Easier version management
- Easier to install
- Harder for us to make

Here's how I would imagine the installation process can go:

```
gem install mustacci

mustacci install --campfire # creates configuration files

mustacci start # starts all services, also available: stop, restart

mustacci worker add # for example
```

Also, I can imagine a plugin system to arise, if `mustacci install` also creates a Gemfile, just like `rails new` does.

This is not an immediate priority, imho.

What do you guys think?

**Comment by marceldegraaf** [comment]
I like it! Would a user install mustacci system-wide? Or once per project?

For Wakoopa I'm working on a CLI Ruby app with the gli gem. Very easy
to set up a nice binary.

On Jun 15, 2012, at 19:04, Iain Hecker
reply@reply.github.com
wrote:
